import { Candle } from '../store/useReplayStore';

export async function fetchSymbolData(symbol: string, timeframe: string): Promise<Candle[]> {
  try {
    // Map the React UI timeframe names
    let interval = '15m';
    if (timeframe === '1 Minute') interval = '1m';
    if (timeframe === '3 Minute') interval = '3m';
    if (timeframe === '5 Minute') interval = '5m';
    if (timeframe === '15 Minute') interval = '15m';
    if (timeframe === '30 Minute') interval = '30m';
    if (timeframe === '1 Hour') interval = '1h';
    if (timeframe === '4 Hour') interval = '4h';
    if (timeframe === '1 Day') interval = '1d';
    if (timeframe === '1 Week') interval = '1w';
    
    // In Phase 6 (Serverless Pipeline), the data is generated by GitHub Actions
    // and saved to public/data/{symbol}_{interval}.json
    const url = `/data/${symbol}_${interval}.json`;
    
    console.log(`Fetching static data from: ${url}`);
    const response = await fetch(url);
    
    if (!response.ok) {
      throw new Error(`Data for ${symbol} at ${interval} not found. Please trigger the GitHub Action and git pull the latest data!`);
    }
    
    const data: Candle[] = await response.json();
    return data;
    
  } catch (error: any) {
    console.error("Failed to fetch static JSON data:", error);
    throw new Error(error.message || "Failed to load data. Ensure you have run the GitHub Action and pulled the files.");
  }
}
